spring:
  datasource:
    url: jdbc:postgresql://dpg-d0o5t2je5dus73b6jujg-a.singapore-postgres.render.com:5432/contracts_db_fpn0?sslmode=require
    username: contracts_db_fpn0_user
    password: rCcvIXepV52lUYFrWJI1e7Fon1LJU2mx
    driver-class-name: org.postgresql.Driver

  data:
    web:
      pageable:
        default-page-size: 2
        max-page-size: 100

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
